<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Mapping\Profiles\UserProfile.cs" />
		<Compile Remove="Services\CacheService.cs" />
		<Compile Remove="Services\EnhancedMapperService.cs" />
		<Compile Remove="Services\JwtService.cs" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="16.2.0" />
		<PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
		<PackageReference Include="MediatR" Version="14.2.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authorization" Version="10.0.10" />
		<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.11" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.10" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.10" />
		<PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.10" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.21.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\WFT.Infra.Application.Contracts\WFT.Infra.Application.Contracts.csproj" />
		<ProjectReference Include="..\WFT.Infra.Core\WFT.Infra.Core.csproj" />
	</ItemGroup>

</Project>
