<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Mapping\Profiles\UserProfile.cs" />
		<Compile Remove="Services\CacheService.cs" />
		<Compile Remove="Services\EnhancedMapperService.cs" />
		<Compile Remove="Services\JwtService.cs" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="15.0.1" />
		<PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
		<PackageReference Include="MediatR" Version="12.5.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authorization" Version="9.0.4" />
		<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.4" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.4" />
		<PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.5" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.9.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\WFT.Infra.Application.Contracts\WFT.Infra.Application.Contracts.csproj" />
		<ProjectReference Include="..\WFT.Infra.Core\WFT.Infra.Core.csproj" />
	</ItemGroup>

</Project>
